/* granting access */
CREATE DATABASE XX_APP_DBNAME IF NOT EXISTS;
CREATE USER IF NOT EXISTS 'XX_APP_USERNAME'@'%' IDENTIFIED BY 'XX_APP_PASSWORD';
GRANT ALL PRIVILEGES ON XX_APP_DBNAME.* TO 'XX_APP_USERNAME'@'%';

