INSERT INTO rol(title) VALUES('ROLE_ADMIN');
INSERT INTO rol(title) VALUES('ROLE_USER');
INSERT INTO country(name,iso2,dial_code) VALUES('Afghanistan (‫افغانستان‬‎)','af','93');

/* initializing a random user */
INSERT INTO personal_info(id,email,fname,lname,phone_no,birth_date,country_iso2,state,city,local) VALUES(UNHEX(REPLACE('f0bf6213-e1ed-412a-9597-b019b00e7468','-','')),'admin@myapp.com','dovahkiin','asseater','+93202101391','1902-01-02','af','Kabol','Kabol','Shirpoor Crossroads, No. 10');

/* setting admin role to him */
INSERT INTO usr(id,uname,passw,personal_info_id) VALUES(UNHEX(REPLACE('14dc7dbc-b1d1-4d27-88ba-0da55e8bd498','-','')),'admin','$2a$12$R3DmJSnjMkv7Q84MoZmrce71DmSebN5JBLzrflnguTrCvwmCdyd56',UNHEX(REPLACE('f0bf6213-e1ed-412a-9597-b019b00e7468','-','')));

/* setting the admin user */
INSERT INTO usr_roles(user_id,roles_title) VALUES(UNHEX(REPLACE('14dc7dbc-b1d1-4d27-88ba-0da55e8bd498','-','')),'ROLE_ADMIN');
INSERT INTO usr_roles(user_id,roles_title) VALUES(UNHEX(REPLACE('14dc7dbc-b1d1-4d27-88ba-0da55e8bd498','-','')),'ROLE_USER');

/* countries */
INSERT INTO country(name,iso2,dial_code) VALUES('Åland Islands','ax','358');
INSERT INTO country(name,iso2,dial_code) VALUES('Albania (Shqipëri)','al','355');
INSERT INTO country(name,iso2,dial_code) VALUES('Algeria (‫الجزائر‬‎)','dz','213');
INSERT INTO country(name,iso2,dial_code) VALUES('American Samoa','as','1684');
INSERT INTO country(name,iso2,dial_code) VALUES('Andorra','ad','376');
INSERT INTO country(name,iso2,dial_code) VALUES('Angola','ao','244');
INSERT INTO country(name,iso2,dial_code) VALUES('Anguilla','ai','1264');
INSERT INTO country(name,iso2,dial_code) VALUES('Antarctica','aq','672');
INSERT INTO country(name,iso2,dial_code) VALUES('Antigua and Barbuda','ag','1268');
INSERT INTO country(name,iso2,dial_code) VALUES('Argentina','ar','54');
INSERT INTO country(name,iso2,dial_code) VALUES('Armenia (Հայաստան)','am','374');
INSERT INTO country(name,iso2,dial_code) VALUES('Aruba','aw','297');
INSERT INTO country(name,iso2,dial_code) VALUES('Australia','au','61');
INSERT INTO country(name,iso2,dial_code) VALUES('Austria (Österreich)','at','43');
INSERT INTO country(name,iso2,dial_code) VALUES('Azerbaijan (Azərbaycan)','az','994');
INSERT INTO country(name,iso2,dial_code) VALUES('Bahamas','bs','1242');
INSERT INTO country(name,iso2,dial_code) VALUES('Bahrain (‫البحرين‬‎)','bh','973');
INSERT INTO country(name,iso2,dial_code) VALUES('Bangladesh (বাংলাদেশ)','bd','880');
INSERT INTO country(name,iso2,dial_code) VALUES('Barbados','bb','1246');
INSERT INTO country(name,iso2,dial_code) VALUES('Belarus (Беларусь)','by','375');
INSERT INTO country(name,iso2,dial_code) VALUES('Belgium (België)','be','32');
INSERT INTO country(name,iso2,dial_code) VALUES('Belize','bz','501');
INSERT INTO country(name,iso2,dial_code) VALUES('Benin (Bénin)','bj','229');
INSERT INTO country(name,iso2,dial_code) VALUES('Bermuda','bm','1441');
INSERT INTO country(name,iso2,dial_code) VALUES('Bhutan (འབྲུག)','bt','975');
INSERT INTO country(name,iso2,dial_code) VALUES('Bolivia','bo','591');
INSERT INTO country(name,iso2,dial_code) VALUES('Bosnia and Herzegovina (Босна и Херцеговина)','ba','387');
INSERT INTO country(name,iso2,dial_code) VALUES('Botswana','bw','267');
INSERT INTO country(name,iso2,dial_code) VALUES('Bouvet Island','bv','47');
INSERT INTO country(name,iso2,dial_code) VALUES('Brazil (Brasil)','br','55');
INSERT INTO country(name,iso2,dial_code) VALUES('British Indian Ocean Territory','io','246');
INSERT INTO country(name,iso2,dial_code) VALUES('British Virgin Islands','vg','1284');
INSERT INTO country(name,iso2,dial_code) VALUES('Brunei','bn','673');
INSERT INTO country(name,iso2,dial_code) VALUES('Bulgaria (България)','bg','359');
INSERT INTO country(name,iso2,dial_code) VALUES('Burkina Faso','bf','226');
INSERT INTO country(name,iso2,dial_code) VALUES('Burundi (Uburundi)','bi','257');
INSERT INTO country(name,iso2,dial_code) VALUES('Cambodia (កម្ពុជា)','kh','855');
INSERT INTO country(name,iso2,dial_code) VALUES('Cameroon (Cameroun)','cm','237');
INSERT INTO country(name,iso2,dial_code) VALUES('Canada','ca','1');
INSERT INTO country(name,iso2,dial_code) VALUES('Cape Verde (Kabu Verdi)','cv','238');
INSERT INTO country(name,iso2,dial_code) VALUES('Caribbean Netherlands','bq','599');
INSERT INTO country(name,iso2,dial_code) VALUES('Cayman Islands','ky','1345');
INSERT INTO country(name,iso2,dial_code) VALUES('Central African Republic (République centrafricaine)','cf','236');
INSERT INTO country(name,iso2,dial_code) VALUES('Chad (Tchad)','td','235');
INSERT INTO country(name,iso2,dial_code) VALUES('Chile','cl','56');
INSERT INTO country(name,iso2,dial_code) VALUES('China (中国)','cn','86');
INSERT INTO country(name,iso2,dial_code) VALUES('Christmas Island','cx','61');
INSERT INTO country(name,iso2,dial_code) VALUES('Cocos (Keeling) Islands','cc','61');
INSERT INTO country(name,iso2,dial_code) VALUES('Colombia','co','57');
INSERT INTO country(name,iso2,dial_code) VALUES('Comoros (‫جزر القمر‬‎)','km','269');
INSERT INTO country(name,iso2,dial_code) VALUES('Congo (DRC) (Jamhuri ya Kidemokrasia ya Kongo)','cd','243');
INSERT INTO country(name,iso2,dial_code) VALUES('Congo (Republic) (Congo-Brazzaville)','cg','242');
INSERT INTO country(name,iso2,dial_code) VALUES('Cook Islands','ck','682');
INSERT INTO country(name,iso2,dial_code) VALUES('Costa Rica','cr','506');
INSERT INTO country(name,iso2,dial_code) VALUES('Côte d’Ivoire','ci','225');
INSERT INTO country(name,iso2,dial_code) VALUES('Croatia (Hrvatska)','hr','385');
INSERT INTO country(name,iso2,dial_code) VALUES('Cuba','cu','53');
INSERT INTO country(name,iso2,dial_code) VALUES('Curaçao','cw','599');
INSERT INTO country(name,iso2,dial_code) VALUES('Cyprus (Κύπρος)','cy','357');
INSERT INTO country(name,iso2,dial_code) VALUES('Czech Republic (Česká republika)','cz','420');
INSERT INTO country(name,iso2,dial_code) VALUES('Denmark (Danmark)','dk','45');
INSERT INTO country(name,iso2,dial_code) VALUES('Djibouti','dj','253');
INSERT INTO country(name,iso2,dial_code) VALUES('Dominica','dm','1767');
INSERT INTO country(name,iso2,dial_code) VALUES('Dominican Republic (República Dominicana)','do','1');
INSERT INTO country(name,iso2,dial_code) VALUES('Ecuador','ec','593');
INSERT INTO country(name,iso2,dial_code) VALUES('Egypt (‫مصر‬‎)','eg','20');
INSERT INTO country(name,iso2,dial_code) VALUES('El Salvador','sv','503');
INSERT INTO country(name,iso2,dial_code) VALUES('Equatorial Guinea (Guinea Ecuatorial)','gq','240');
INSERT INTO country(name,iso2,dial_code) VALUES('Eritrea','er','291');
INSERT INTO country(name,iso2,dial_code) VALUES('Estonia (Eesti)','ee','372');
INSERT INTO country(name,iso2,dial_code) VALUES('Ethiopia','et','251');
INSERT INTO country(name,iso2,dial_code) VALUES('Falkland Islands (Islas Malvinas)','fk','500');
INSERT INTO country(name,iso2,dial_code) VALUES('Faroe Islands (Føroyar)','fo','298');
INSERT INTO country(name,iso2,dial_code) VALUES('Fiji','fj','679');
INSERT INTO country(name,iso2,dial_code) VALUES('Finland (Suomi)','fi','358');
INSERT INTO country(name,iso2,dial_code) VALUES('France','fr','33');
INSERT INTO country(name,iso2,dial_code) VALUES('French Guiana (Guyane française)','gf','594');
INSERT INTO country(name,iso2,dial_code) VALUES('French Polynesia (Polynésie française)','pf','689');
INSERT INTO country(name,iso2,dial_code) VALUES('French Southern and Antarctic Lands','tf','262');
INSERT INTO country(name,iso2,dial_code) VALUES('Gabon','ga','241');
INSERT INTO country(name,iso2,dial_code) VALUES('Gambia','gm','220');
INSERT INTO country(name,iso2,dial_code) VALUES('Georgia (საქართველო)','ge','995');
INSERT INTO country(name,iso2,dial_code) VALUES('Germany (Deutschland)','de','49');
INSERT INTO country(name,iso2,dial_code) VALUES('Ghana (Gaana)','gh','233');
INSERT INTO country(name,iso2,dial_code) VALUES('Gibraltar','gi','350');
INSERT INTO country(name,iso2,dial_code) VALUES('Greece (Ελλάδα)','gr','30');
INSERT INTO country(name,iso2,dial_code) VALUES('Greenland (Kalaallit Nunaat)','gl','299');
INSERT INTO country(name,iso2,dial_code) VALUES('Grenada','gd','1473');
INSERT INTO country(name,iso2,dial_code) VALUES('Guadeloupe','gp','590');
INSERT INTO country(name,iso2,dial_code) VALUES('Guam','gu','1671');
INSERT INTO country(name,iso2,dial_code) VALUES('Guatemala','gt','502');
INSERT INTO country(name,iso2,dial_code) VALUES('Guernsey','gg','44');
INSERT INTO country(name,iso2,dial_code) VALUES('Guinea (Guinée)','gn','224');
INSERT INTO country(name,iso2,dial_code) VALUES('Guinea-Bissau (Guiné Bissau)','gw','245');
INSERT INTO country(name,iso2,dial_code) VALUES('Guyana','gy','592');
INSERT INTO country(name,iso2,dial_code) VALUES('Haiti','ht','509');
INSERT INTO country(name,iso2,dial_code) VALUES('Heard Island and McDonald Islands','hm','672');
INSERT INTO country(name,iso2,dial_code) VALUES('Honduras','hn','504');
INSERT INTO country(name,iso2,dial_code) VALUES('Hong Kong (香港)','hk','852');
INSERT INTO country(name,iso2,dial_code) VALUES('Hungary (Magyarország)','hu','36');
INSERT INTO country(name,iso2,dial_code) VALUES('Iceland (Ísland)','is','354');
INSERT INTO country(name,iso2,dial_code) VALUES('India (भारत)','in','91');
INSERT INTO country(name,iso2,dial_code) VALUES('Indonesia','id','62');
INSERT INTO country(name,iso2,dial_code) VALUES('Iran (‫ایران‬‎)','ir','98');
INSERT INTO country(name,iso2,dial_code) VALUES('Iraq (‫العراق‬‎)','iq','964');
INSERT INTO country(name,iso2,dial_code) VALUES('Ireland','ie','353');
INSERT INTO country(name,iso2,dial_code) VALUES('Isle of Man','im','44');
INSERT INTO country(name,iso2,dial_code) VALUES('Israel (‫ישראל‬‎)','il','972');
INSERT INTO country(name,iso2,dial_code) VALUES('Italy (Italia)','it','39');
INSERT INTO country(name,iso2,dial_code) VALUES('Jamaica','jm','1876');
INSERT INTO country(name,iso2,dial_code) VALUES('Japan (日本)','jp','81');
INSERT INTO country(name,iso2,dial_code) VALUES('Jersey','je','44');
INSERT INTO country(name,iso2,dial_code) VALUES('Jordan (‫الأردن‬‎)','jo','962');
INSERT INTO country(name,iso2,dial_code) VALUES('Kazakhstan (Казахстан)','kz','7');
INSERT INTO country(name,iso2,dial_code) VALUES('Kenya','ke','254');
INSERT INTO country(name,iso2,dial_code) VALUES('Kiribati','ki','686');
INSERT INTO country(name,iso2,dial_code) VALUES('Kosovo','xk','383');
INSERT INTO country(name,iso2,dial_code) VALUES('Kuwait (‫الكويت‬‎)','kw','965');
INSERT INTO country(name,iso2,dial_code) VALUES('Kyrgyzstan (Кыргызстан)','kg','996');
INSERT INTO country(name,iso2,dial_code) VALUES('Laos (ລາວ)','la','856');
INSERT INTO country(name,iso2,dial_code) VALUES('Latvia (Latvija)','lv','371');
INSERT INTO country(name,iso2,dial_code) VALUES('Lebanon (‫لبنان‬‎)','lb','961');
INSERT INTO country(name,iso2,dial_code) VALUES('Lesotho','ls','266');
INSERT INTO country(name,iso2,dial_code) VALUES('Liberia','lr','231');
INSERT INTO country(name,iso2,dial_code) VALUES('Libya (‫ليبيا‬‎)','ly','218');
INSERT INTO country(name,iso2,dial_code) VALUES('Liechtenstein','li','423');
INSERT INTO country(name,iso2,dial_code) VALUES('Lithuania (Lietuva)','lt','370');
INSERT INTO country(name,iso2,dial_code) VALUES('Luxembourg','lu','352');
INSERT INTO country(name,iso2,dial_code) VALUES('Macau (澳門)','mo','853');
INSERT INTO country(name,iso2,dial_code) VALUES('Macedonia (FYROM) (Македонија)','mk','389');
INSERT INTO country(name,iso2,dial_code) VALUES('Madagascar (Madagasikara)','mg','261');
INSERT INTO country(name,iso2,dial_code) VALUES('Malawi','mw','265');
INSERT INTO country(name,iso2,dial_code) VALUES('Malaysia','my','60');
INSERT INTO country(name,iso2,dial_code) VALUES('Maldives','mv','960');
INSERT INTO country(name,iso2,dial_code) VALUES('Mali','ml','223');
INSERT INTO country(name,iso2,dial_code) VALUES('Malta','mt','356');
INSERT INTO country(name,iso2,dial_code) VALUES('Marshall Islands','mh','692');
INSERT INTO country(name,iso2,dial_code) VALUES('Martinique','mq','596');
INSERT INTO country(name,iso2,dial_code) VALUES('Mauritania (‫موريتانيا‬‎)','mr','222');
INSERT INTO country(name,iso2,dial_code) VALUES('Mauritius (Moris)','mu','230');
INSERT INTO country(name,iso2,dial_code) VALUES('Mayotte','yt','262');
INSERT INTO country(name,iso2,dial_code) VALUES('Mexico (México)','mx','52');
INSERT INTO country(name,iso2,dial_code) VALUES('Micronesia','fm','691');
INSERT INTO country(name,iso2,dial_code) VALUES('Moldova (Republica Moldova)','md','373');
INSERT INTO country(name,iso2,dial_code) VALUES('Monaco','mc','377');
INSERT INTO country(name,iso2,dial_code) VALUES('Mongolia (Монгол)','mn','976');
INSERT INTO country(name,iso2,dial_code) VALUES('Montenegro (Crna Gora)','me','382');
INSERT INTO country(name,iso2,dial_code) VALUES('Montserrat','ms','1664');
INSERT INTO country(name,iso2,dial_code) VALUES('Morocco (‫المغرب‬‎)','ma','212');
INSERT INTO country(name,iso2,dial_code) VALUES('Mozambique (Moçambique)','mz','258');
INSERT INTO country(name,iso2,dial_code) VALUES('Myanmar (Burma) (မြန်မာ)','mm','95');
INSERT INTO country(name,iso2,dial_code) VALUES('Namibia (Namibië)','na','264');
INSERT INTO country(name,iso2,dial_code) VALUES('Nauru','nr','674');
INSERT INTO country(name,iso2,dial_code) VALUES('Nepal (नेपाल)','np','977');
INSERT INTO country(name,iso2,dial_code) VALUES('Netherlands (Nederland)','nl','31');
INSERT INTO country(name,iso2,dial_code) VALUES('New Caledonia (Nouvelle-Calédonie)','nc','687');
INSERT INTO country(name,iso2,dial_code) VALUES('New Zealand','nz','64');
INSERT INTO country(name,iso2,dial_code) VALUES('Nicaragua','ni','505');
INSERT INTO country(name,iso2,dial_code) VALUES('Niger (Nijar)','ne','227');
INSERT INTO country(name,iso2,dial_code) VALUES('Nigeria','ng','234');
INSERT INTO country(name,iso2,dial_code) VALUES('Niue','nu','683');
INSERT INTO country(name,iso2,dial_code) VALUES('Norfolk Island','nf','672');
INSERT INTO country(name,iso2,dial_code) VALUES('North Korea (조선 민주주의 인민 공화국)','kp','850');
INSERT INTO country(name,iso2,dial_code) VALUES('Northern Mariana Islands','mp','1670');
INSERT INTO country(name,iso2,dial_code) VALUES('Norway (Norge)','no','47');
INSERT INTO country(name,iso2,dial_code) VALUES('Oman (‫عُمان‬‎)','om','968');
INSERT INTO country(name,iso2,dial_code) VALUES('Pakistan (‫پاکستان‬‎)','pk','92');
INSERT INTO country(name,iso2,dial_code) VALUES('Palau','pw','680');
INSERT INTO country(name,iso2,dial_code) VALUES('Palestine (‫فلسطين‬‎)','ps','970');
INSERT INTO country(name,iso2,dial_code) VALUES('Panama (Panamá)','pa','507');
INSERT INTO country(name,iso2,dial_code) VALUES('Papua New Guinea','pg','675');
INSERT INTO country(name,iso2,dial_code) VALUES('Paraguay','py','595');
INSERT INTO country(name,iso2,dial_code) VALUES('Peru (Perú)','pe','51');
INSERT INTO country(name,iso2,dial_code) VALUES('Philippines','ph','63');
INSERT INTO country(name,iso2,dial_code) VALUES('Pitcairn Islands','pn','64');
INSERT INTO country(name,iso2,dial_code) VALUES('Poland (Polska)','pl','48');
INSERT INTO country(name,iso2,dial_code) VALUES('Portugal','pt','351');
INSERT INTO country(name,iso2,dial_code) VALUES('Puerto Rico','pr','1');
INSERT INTO country(name,iso2,dial_code) VALUES('Qatar (‫قطر‬‎)','qa','974');
INSERT INTO country(name,iso2,dial_code) VALUES('Réunion (La Réunion)','re','262');
INSERT INTO country(name,iso2,dial_code) VALUES('Romania (România)','ro','40');
INSERT INTO country(name,iso2,dial_code) VALUES('Russia (Россия)','ru','7');
INSERT INTO country(name,iso2,dial_code) VALUES('Rwanda','rw','250');
INSERT INTO country(name,iso2,dial_code) VALUES('Saint Barthélemy (Saint-Barthélemy)','bl','590');
INSERT INTO country(name,iso2,dial_code) VALUES('Saint Helena','sh','290');
INSERT INTO country(name,iso2,dial_code) VALUES('Saint Kitts and Nevis','kn','1869');
INSERT INTO country(name,iso2,dial_code) VALUES('Saint Lucia','lc','1758');
INSERT INTO country(name,iso2,dial_code) VALUES('Saint Martin (Saint-Martin (partie française))','mf','590');
INSERT INTO country(name,iso2,dial_code) VALUES('Saint Pierre and Miquelon (Saint-Pierre-et-Miquelon)','pm','508');
INSERT INTO country(name,iso2,dial_code) VALUES('Saint Vincent and the Grenadines','vc','1784');
INSERT INTO country(name,iso2,dial_code) VALUES('Samoa','ws','685');
INSERT INTO country(name,iso2,dial_code) VALUES('San Marino','sm','378');
INSERT INTO country(name,iso2,dial_code) VALUES('São Tomé and Príncipe (São Tomé e Príncipe)','st','239');
INSERT INTO country(name,iso2,dial_code) VALUES('Saudi Arabia (‫المملكة العربية السعودية‬‎)','sa','966');
INSERT INTO country(name,iso2,dial_code) VALUES('Senegal (Sénégal)','sn','221');
INSERT INTO country(name,iso2,dial_code) VALUES('Serbia (Србија)','rs','381');
INSERT INTO country(name,iso2,dial_code) VALUES('Seychelles','sc','248');
INSERT INTO country(name,iso2,dial_code) VALUES('Sierra Leone','sl','232');
INSERT INTO country(name,iso2,dial_code) VALUES('Singapore','sg','65');
INSERT INTO country(name,iso2,dial_code) VALUES('Sint Maarten','sx','1721');
INSERT INTO country(name,iso2,dial_code) VALUES('Slovakia (Slovensko)','sk','421');
INSERT INTO country(name,iso2,dial_code) VALUES('Slovenia (Slovenija)','si','386');
INSERT INTO country(name,iso2,dial_code) VALUES('Solomon Islands','sb','677');
INSERT INTO country(name,iso2,dial_code) VALUES('Somalia (Soomaaliya)','so','252');
INSERT INTO country(name,iso2,dial_code) VALUES('South Africa','za','27');
INSERT INTO country(name,iso2,dial_code) VALUES('South Georgia and the South Sandwich Islands','gs','500');
INSERT INTO country(name,iso2,dial_code) VALUES('South Korea (대한민국)','kr','82');
INSERT INTO country(name,iso2,dial_code) VALUES('South Sudan (‫جنوب السودان‬‎)','ss','211');
INSERT INTO country(name,iso2,dial_code) VALUES('Spain (España)','es','34');
INSERT INTO country(name,iso2,dial_code) VALUES('Sri Lanka (ශ්‍රී ලංකාව)','lk','94');
INSERT INTO country(name,iso2,dial_code) VALUES('Sudan (‫السودان‬‎)','sd','249');
INSERT INTO country(name,iso2,dial_code) VALUES('Suriname','sr','597');
INSERT INTO country(name,iso2,dial_code) VALUES('Svalbard and Jan Mayen','sj','47');
INSERT INTO country(name,iso2,dial_code) VALUES('Swaziland','sz','268');
INSERT INTO country(name,iso2,dial_code) VALUES('Sweden (Sverige)','se','46');
INSERT INTO country(name,iso2,dial_code) VALUES('Switzerland (Schweiz)','ch','41');
INSERT INTO country(name,iso2,dial_code) VALUES('Syria (‫سوريا‬‎)','sy','963');
INSERT INTO country(name,iso2,dial_code) VALUES('Taiwan (台灣)','tw','886');
INSERT INTO country(name,iso2,dial_code) VALUES('Tajikistan','tj','992');
INSERT INTO country(name,iso2,dial_code) VALUES('Tanzania','tz','255');
INSERT INTO country(name,iso2,dial_code) VALUES('Thailand (ไทย)','th','66');
INSERT INTO country(name,iso2,dial_code) VALUES('Timor-Leste','tl','670');
INSERT INTO country(name,iso2,dial_code) VALUES('Togo','tg','228');
INSERT INTO country(name,iso2,dial_code) VALUES('Tokelau','tk','690');
INSERT INTO country(name,iso2,dial_code) VALUES('Tonga','to','676');
INSERT INTO country(name,iso2,dial_code) VALUES('Trinidad and Tobago','tt','1868');
INSERT INTO country(name,iso2,dial_code) VALUES('Tunisia (‫تونس‬‎)','tn','216');
INSERT INTO country(name,iso2,dial_code) VALUES('Turkey (Türkiye)','tr','90');
INSERT INTO country(name,iso2,dial_code) VALUES('Turkmenistan','tm','993');
INSERT INTO country(name,iso2,dial_code) VALUES('Turks and Caicos Islands','tc','1649');
INSERT INTO country(name,iso2,dial_code) VALUES('Tuvalu','tv','688');
INSERT INTO country(name,iso2,dial_code) VALUES('U.S. Virgin Islands','vi','1340');
INSERT INTO country(name,iso2,dial_code) VALUES('Uganda','ug','256');
INSERT INTO country(name,iso2,dial_code) VALUES('Ukraine (Україна)','ua','380');
INSERT INTO country(name,iso2,dial_code) VALUES('United Arab Emirates (‫الإمارات العربية المتحدة‬‎)','ae','971');
INSERT INTO country(name,iso2,dial_code) VALUES('United Kingdom','gb','44');
INSERT INTO country(name,iso2,dial_code) VALUES('United States','us','1');
INSERT INTO country(name,iso2,dial_code) VALUES('United States Minor Outlying Islands','um','1');
INSERT INTO country(name,iso2,dial_code) VALUES('Uruguay','uy','598');
INSERT INTO country(name,iso2,dial_code) VALUES('Uzbekistan (Oʻzbekiston)','uz','998');
INSERT INTO country(name,iso2,dial_code) VALUES('Vanuatu','vu','678');
INSERT INTO country(name,iso2,dial_code) VALUES('Vatican City (Città del Vaticano)','va','39');
INSERT INTO country(name,iso2,dial_code) VALUES('Venezuela','ve','58');
INSERT INTO country(name,iso2,dial_code) VALUES('Vietnam (Việt Nam)','vn','84');
INSERT INTO country(name,iso2,dial_code) VALUES('Wallis and Futuna','wf','681');
INSERT INTO country(name,iso2,dial_code) VALUES('Western Sahara','eh','212');
INSERT INTO country(name,iso2,dial_code) VALUES('Yemen (‫اليمن‬‎)','ye','967');
INSERT INTO country(name,iso2,dial_code) VALUES('Zambia','zm','260');
INSERT INTO country(name,iso2,dial_code) VALUES('Zimbabwe','zw','263');
